modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"
issueTrackerURL = "https://github.com/Wesley1808/ServerCore/issues"

[[mods]]
modId = "servercore"
version = "${version}"
displayName = "ServerCore"
displayURL = "https://github.com/Wesley1808/ServerCore"
logoFile = "assets/servercore/icon.png"
authors = "Wesley1808"

description = '''
A forge mod that aims to optimize the minecraft server.
'''

[[dependencies.servercore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
