modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/Wesley1808/ServerCore/issues"
showAsResourcePack = false

[[mods]]
modId = "servercore"
version = "${version}"
displayName = "ServerCore"
displayURL = "https://github.com/Wesley1808/ServerCore"
logoFile = "icon.png"
authors = "Wesley1808"

description = '''
A NeoForge mod that aims to optimize the minecraft server.
'''

[[mixins]]
config = "servercore.common.mixins.json"

[[dependencies.servercore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.servercore]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2.86,)"
ordering = "NONE"
side = "BOTH"